version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: "/src"
    volumes:
      - "./src:/src"
      - node_modules_volume:/src/node_modules
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true
    - NODE_ENV=development
    - NODE_OPTIONS=--openssl-legacy-provider
    command: './scripts/compose_command.bash'
volumes:
  node_modules_volume: